# Assignment 2: Pandas DataFrame Creation

This notebook contains how to create a Pandas DataFrame, filter data, and add a new calculated column.

In [1]:
import pandas as pd

In [2]:
# Creating a dictionary containing employee information
employee_data = {
    "Name": ["Rahul", "Priya", "Amit", "Anuj"],
    "Age": [25, 30, 28, 35],
    "Department": ["HR", "IT", "Finance", "IT"],
    "Salary": [30000, 50000, 45000, 60000]
}

# Converting the dictionary into a Pandas DataFrame
dataframe = pd.DataFrame(employee_data)

print("Employee DataFrame:")
dataframe

Employee DataFrame:

    Name  Age Department  Salary
0  Rahul   25         HR   30000
1  Priya   30         IT   50000
2   Amit   28    Finance   45000
3   Anuj   35         IT   60000

In [3]:
# Displaying the first two rows
print("First Two Rows:")
dataframe.head(2)

First Two Rows:

    Name  Age Department  Salary
0  Rahul   25         HR   30000
1  Priya   30         IT   50000

In [4]:
# Showing summary statistics
print("Summary Statistics:")
dataframe.describe()

Summary Statistics:

             Age   Salary
count   4.000000      4.0
mean   29.500000  46250.0
std     4.203173  12500.0
min    25.000000  30000.0
25%    27.250000  41250.0
50%    29.000000  47500.0
75%    31.250000  52500.0
max    35.000000  60000.0

In [5]:
# Showing employees who belong to the IT department
it_employees = dataframe[dataframe["Department"] == "IT"]

print("IT Employees:")
it_employees

IT Employees:

    Name  Age Department  Salary
1  Priya   30         IT   50000
3   Anuj   35         IT   60000

In [6]:
# Adding new column: Bonus = Salary * 0.10
dataframe["Bonus"] = dataframe["Salary"] * 0.10

print("Updated DataFrame with Bonus:")
dataframe

Updated DataFrame with Bonus:

    Name  Age Department  Salary   Bonus
0  Rahul   25         HR   30000  3000.0
1  Priya   30         IT   50000  5000.0
2   Amit   28    Finance   45000  4500.0
3   Anuj   35         IT   60000  6000.0