# Assignment 3: Data Cleaning

This notebook contains how to detect missing values and clean a dataset
using Pandas by replacing missing entries with appropriate values.

In [1]:
# Importing the required libraries
import pandas as pd
import numpy as np

In [2]:
# Creating a dataset containing missing values
employee_data = {
    "Name": ["Rahul", "Priya", "Anuj"],
    "Age": [25, np.nan, 29],
    "Salary": [30000, 40000, np.nan]
}

dataframe = pd.DataFrame(employee_data)

print("Original DataFrame:")
dataframe

Original DataFrame:

    Name   Age   Salary
0  Rahul  25.0  30000.0
1  Priya   NaN  40000.0
2   Anuj  29.0      NaN

In [3]:
# Detecting missing values
print("Missing Values:")
dataframe.isnull()

Missing Values:

    Name    Age  Salary
0  False  False   False
1  False   True   False
2  False  False    True

In [4]:
# Replacing missing values in the Age column with the mean value of age
average_age = dataframe["Age"].mean()

dataframe["Age"] = dataframe["Age"].fillna(average_age)

print("DataFrame after replacing missing Age:")
dataframe

DataFrame after replacing missing Age:

    Name   Age   Salary
0  Rahul  25.0  30000.0
1  Priya  27.0  40000.0
2   Anuj  29.0      NaN

In [7]:
# Replacing missing salary values with 0
dataframe["Salary"] = dataframe["Salary"].fillna(0)

print("DataFrame:")
dataframe

DataFrame:

    Name   Age   Salary
0  Rahul  25.0  30000.0
1  Priya  27.0  40000.0
2   Anuj  29.0      0.0